import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://i0.wp.com/urbanfits.store/wp-content/uploads/2022/09/cropped-U-logo1-2.png?fit=32%2C32&amp;ssl=1" sizes="32x32"></link>
        <link rel="icon" href="https://i0.wp.com/urbanfits.store/wp-content/uploads/2022/09/cropped-U-logo1-2.png?fit=192%2C192&amp;ssl=1" sizes="192x192"></link>
        <link rel="apple-touch-icon" href="https://i0.wp.com/urbanfits.store/wp-content/uploads/2022/09/cropped-U-logo1-2.png?fit=180%2C180&amp;ssl=1"></link>
      </Head>
      <main className={styles.main}>
        hellow this is me 
        <Link href="/login">go to sign up page</Link>
      </main>
    </>
  )
}
